# This playbook will pull the nginx image from dockerhub, install unzip, download static content, then serve to port 80 on localhost 


# Make sure Docker is installed and running 

- hosts: localhost
  become: true
  tasks:
    - name: apt update
      apt: update_cache=yes
    - name: Install Docker Engine
      apt:
        name: docker.io
        state: present
    - name: Install Docker CLI
      apt:
        name: docker-compose
        state: present
    - name: Install pip3
      apt:
        name: python3-pip
        state: present
    - name: pip3 docker
      command: "pip3 install docker"
    - name: Install Unzip package
      apt:
        name: unzip
        state: present

    #- name: Start Docker service (WSL issue here)
    #  service:
    #    name: docker
    #    state: started
    #    enabled: true

    - name: Pull nginx Docker image
      docker_image:
        name: nginx
        source: pull

    - name: Run nginx Docker container
      docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"
    - name: Add host to group 'containers' #with variable foo=42
      add_host:
        name: nginx
        groups: containers
        #foo: 42

# Download and unzip static content

- hosts: containers 
  become: true
  tasks:
    - name: Download a file
      get_url:
        url: https://html5up.net/massively/download
        dest: /var/www/html/
    - name: Unzip archive
      unarchive:
        src: /var/www/html/webtemplate
        dest: /var/www/html/
        remote_src: true
        extra_opts: "-q" # optional: quiet mode
    - name: Restart Nginx service
      service:
        name: nginx
        state: restarted
